# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: v13 Main - Pre-release

on:
  push:
    tags:
    - "v13.[0-9]+.[0-9]+-[a-z]*[0-9][0-9][0-9]"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
        
    - name: Pack Core Project
      run: dotnet pack src/Method4.UmbracoMigrator.Target.Core/Method4.UmbracoMigrator.Target.Core.csproj --configuration Release /p:Version=${VERSION} --output .
      
    - name: Pack Main Project
      run: dotnet pack src/Method4.UmbracoMigrator.Target/Method4.UmbracoMigrator.Target.csproj --configuration Release /p:Version=${VERSION} --output .
      
    - name: Push Core Project
      run: dotnet nuget push Method4.UmbracoMigrator.Target.Core.${VERSION}.nupkg --api-key ${NUGET_API_KEY} --source https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        
    - name: Push Main Project
      run: dotnet nuget push Method4.UmbracoMigrator.Target.${VERSION}.nupkg --api-key ${NUGET_API_KEY} --source https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
