# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: v13 Main - Build

on:
  push:
    branches: [ "v13/main" ]
  pull_request:
    branches: [ "v13/main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/Method4.UmbracoMigrator.Target.sln
    - name: Build
      run: dotnet build src/Method4.UmbracoMigrator.Target.sln --no-restore --configuration Release
